import { Dog } from 'lucide-react';
import { CustomerNavigation } from '@/components/customer-navigation';
import '@/components/customer-pages.css';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { isSupabaseConfigured } from '@/lib/supabase/config';
import { createClient } from '@/lib/supabase/server';
import { formatOsloDateTime } from '@/lib/oslo-time';

function dateTime(value: string) { return new Intl.DateTimeFormat('nb-NO', { weekday:'short', day:'numeric', month:'short', hour:'2-digit', minute:'2-digit', timeZone:'Europe/Oslo' }).format(new Date(value)); }
function ageText(birthDate: string | null) { if (!birthDate) return null; const birth=new Date(`${birthDate}T12:00:00`); const now=new Date(); let months=(now.getFullYear()-birth.getFullYear())*12+now.getMonth()-birth.getMonth(); if(now.getDate()<birth.getDate()) months-=1; if(months<0)return null; if(months<24)return `${months} mnd`; return `${Math.floor(months/12)} år`; }
const statusText: Record<string,string> = { pending:'Venter på treneren', confirmed:'Bekreftet', reschedule_offered:'Svar på ny tid', declined_by_trainer:'Avslått', cancelled_by_customer:'Avsluttet', refunded:'Refundert', completed:'Fullført' };
const groupStatusText: Record<string,string> = { checkout_pending:'Venter på betaling', confirmed:'Påmeldt', cancelled:'Avbestilt', refunded:'Refundert', completed:'Fullført' };

type MiniTrainer = { id:string; business_name:string; slug:string };
type MiniOffering = { id:string; title:string; kind:string; trainer_id:string };
type MiniSession = { offering_id:string; starts_at:string };

export default async function AccountPage() {
  if (!isSupabaseConfigured()) return <main className="page-shell narrow customer-page"><CustomerNavigation current="/account" /><section className="setup-card"><h1>Supabase er ikke koblet til ennå</h1></section></main>;
  const supabase=await createClient(); const { data:{ user } }=await supabase.auth.getUser(); if(!user) redirect('/login?next=/account');
  const [{data:profile},{data:trainerAccount},{data:dogs},{data:bookings},{data:groupEnrollments},{data:onlinePurchases},{data:waitlist}] = await Promise.all([
    supabase.from('profiles').select('display_name, role').eq('id',user.id).maybeSingle(),
    supabase.from('trainer_profiles').select('business_name, slug, verification_status, verification_review_note').eq('id',user.id).maybeSingle(),
    supabase.from('dogs').select('id, name, breed, birth_date, sex').eq('owner_id',user.id).order('created_at'),
    supabase.from('bookings').select('id, trainer_id, service_id, dog_id, status, payment_status, requested_starts_at, subtotal_nok, service_fee_nok, dog_name, expired_at, refund_status').eq('customer_id',user.id).order('created_at',{ascending:false}),
    supabase.from('group_enrollments').select('id, offering_id, dog_id, dog_name, status, payment_status, subtotal_nok, service_fee_nok, created_at').eq('customer_id',user.id).order('created_at',{ascending:false}),
    supabase.from('online_course_purchases').select('id, course_id, dog_name, status, payment_status, subtotal_nok, service_fee_nok, purchased_at, created_at, course_completed_at, certificate_id').eq('customer_id',user.id).eq('status','active').eq('payment_status','captured').order('purchased_at',{ascending:false}),
    supabase.from('group_waitlist').select('id, offering_id, dog_name, status, joined_at, offer_expires_at').eq('customer_id',user.id).in('status',['waiting','offered','checkout']).order('joined_at'),
  ]);

  const serviceIds=[...new Set((bookings||[]).map(b=>b.service_id))]; const trainerIds=[...new Set((bookings||[]).map(b=>b.trainer_id))]; const bookingIds=(bookings||[]).map(b=>b.id);
  const offeringIds=[...new Set([...(groupEnrollments||[]).map(e=>e.offering_id), ...(waitlist||[]).map(w=>w.offering_id)])];
  const onlineCourseIds=[...new Set((onlinePurchases||[]).map(p=>p.course_id))];
  const [{data:services},{data:trainers},{data:reviews},{data:offerings},{data:groupSessions},{data:onlineCourses},{data:lessonNotes}] = await Promise.all([
    serviceIds.length?supabase.from('services').select('id,title').in('id',serviceIds):Promise.resolve({data:[] as {id:string;title:string}[]}),
    trainerIds.length?supabase.from('trainer_profiles').select('id,business_name,slug').in('id',trainerIds):Promise.resolve({data:[] as {id:string;business_name:string;slug:string}[]}),
    bookingIds.length?supabase.from('reviews').select('booking_id').in('booking_id',bookingIds):Promise.resolve({data:[] as {booking_id:string}[]}),
    offeringIds.length?supabase.from('group_offerings').select('id,title,kind,trainer_id').in('id',offeringIds):Promise.resolve({data:[] as {id:string;title:string;kind:string;trainer_id:string}[]}),
    offeringIds.length?supabase.from('group_sessions').select('offering_id,starts_at').in('offering_id',offeringIds).order('starts_at'):Promise.resolve({data:[] as {offering_id:string;starts_at:string}[]}),
    onlineCourseIds.length?supabase.from('online_courses').select('id,title,slug,trainer_id,cover_image_url').in('id',onlineCourseIds):Promise.resolve({data:[] as {id:string;title:string;slug:string;trainer_id:string;cover_image_url:string|null}[]}),
    bookingIds.length?supabase.from('lesson_shared_notes').select('booking_id,published_at').in('booking_id',bookingIds).not('published_at','is',null):Promise.resolve({data:[] as {booking_id:string;published_at:string|null}[]}),
  ]);
  const groupTrainerIds=[...new Set((offerings||[]).map(o=>o.trainer_id))];
  const onlineTrainerIds=[...new Set((onlineCourses||[]).map(c=>c.trainer_id))];
  const {data:groupTrainers}=groupTrainerIds.length?await supabase.from('trainer_profiles').select('id,business_name,slug').in('id',groupTrainerIds):{data:[] as {id:string;business_name:string;slug:string}[]};
  const {data:onlineTrainers}=onlineTrainerIds.length?await supabase.from('trainer_profiles').select('id,business_name,slug').in('id',onlineTrainerIds):{data:[] as {id:string;business_name:string;slug:string}[]};
  const serviceMap=new Map((services||[]).map(s=>[s.id,s.title])); const trainerMap=new Map<string, MiniTrainer>(((trainers||[]) as MiniTrainer[]).map(t=>[t.id,t])); const reviewedBookings=new Set((reviews||[]).map(r=>r.booking_id)); const bookingsWithLessonNotes=new Set((lessonNotes||[]).map(n=>n.booking_id));
  const offeringMap=new Map<string, MiniOffering>(((offerings||[]) as MiniOffering[]).map(o=>[o.id,o])); const groupTrainerMap=new Map<string, MiniTrainer>(((groupTrainers||[]) as MiniTrainer[]).map(t=>[t.id,t]));
  const onlineCourseMap=new Map((onlineCourses||[]).map(c=>[c.id,c])); const onlineTrainerMap=new Map<string,MiniTrainer>(((onlineTrainers||[]) as MiniTrainer[]).map(t=>[t.id,t]));

  const upcoming = [
    ...(bookings || []).filter(b => b.status === 'confirmed' && !b.expired_at && new Date(b.requested_starts_at).getTime() > Date.now()).map(b => ({ id: b.id, startsAt: b.requested_starts_at, title: serviceMap.get(b.service_id) || 'Privattime', dog: b.dog_name, href: '/booking/' + b.id })),
    ...(groupEnrollments || []).filter(e => e.status === 'confirmed').flatMap(e => { const next = (groupSessions || []).find(s => s.offering_id === e.offering_id && new Date(s.starts_at).getTime() > Date.now()); return next ? [{ id: e.id, startsAt: next.starts_at, title: offeringMap.get(e.offering_id)?.title || 'Kurs', dog: e.dog_name, href: '/activity-booking/' + e.id }] : []; }),
  ].sort((a,b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime());
  const nextAppointment = upcoming[0];
  const needsResponse = (bookings || []).filter(b => b.status === 'reschedule_offered' && !b.expired_at);
  const availablePlaces = (waitlist || []).filter(w => w.status === 'offered' && (!w.offer_expires_at || new Date(w.offer_expires_at).getTime() > Date.now()));

  return <main className="page-shell narrow customer-page"><CustomerNavigation current="/account" />
    <section className="page-heading"><span className="eyebrow">Min side</span><h1>Hei, {profile?.display_name||'hundeeier'}</h1><p className="muted">Hundene, privattimene, kursene og nettkursene dine samles her.</p></section>

    <div className="hub-overview"><section className="hub-next"><span>{nextAppointment ? 'Neste avtale' : 'Din neste trening'}</span><h2>{nextAppointment?.title || 'Finn trening som passer dere'}</h2>{nextAppointment ? <><strong>{dateTime(nextAppointment.startsAt)}</strong><p>{nextAppointment.dog || 'Hund'}{upcoming.length > 1 ? ' · ' + upcoming.length + ' kommende avtaler' : ''}</p><Link className="btn" href={nextAppointment.href}>Se avtalen</Link></> : <><p>Når du har en bekreftet time eller kurspåmelding, finner du neste avtale her.</p><Link className="btn" href="/discover">Finn hundetrening</Link></>}</section><div className="hub-shortcuts"><Link href="/messages"><strong>Meldinger</strong><span>Spørsmål og oppfølging fra treneren →</span></Link><Link href="/saved"><strong>Lagret</strong><span>Trenere og kurs du vil finne igjen →</span></Link><Link href="#nettkurs"><strong>Mine nettkurs</strong><span>{(onlinePurchases || []).length ? (onlinePurchases || []).length + ' kurs tilgjengelig · fortsett treningen →' : 'Se kursene dine →'}</span></Link></div></div>
    {needsResponse.length || availablePlaces.length ? <section className="hub-attention"><h2>Venter på svar fra deg</h2>{needsResponse.map(b => <Link key={b.id} href={'/booking/' + b.id}>Ny tid foreslått: {serviceMap.get(b.service_id) || 'Privattime'}</Link>)}{availablePlaces.map(w => <Link key={w.id} href={'/activities/' + w.offering_id}>Plass tilgjengelig: {offeringMap.get(w.offering_id)?.title || 'Kurs'}</Link>)}</section> : null}
    <nav className="hub-section-links" aria-label="Dine bestillinger"><a href="#hunder">Hunder</a><a href="#privattimer">Privattimer</a><a href="#nettkurs">Nettkurs</a><a href="#gruppekurs">Kurs og arrangementer</a></nav>
    {trainerAccount ? <section className="dashboard-section"><div className="section-title"><div><span className="eyebrow">Trenerområde</span><h2>{trainerAccount.verification_status === 'approved' ? 'Hundetrener på Hundetimer' : trainerAccount.verification_status === 'pending' ? 'Søknaden din er til vurdering' : trainerAccount.verification_status === 'rejected' ? 'Søknaden trenger endringer' : trainerAccount.verification_status === 'suspended' ? 'Trenerprofilen er midlertidig skjult' : 'Trenersøknad'}</h2></div>{profile?.role === 'trainer' && ['approved','suspended'].includes(trainerAccount.verification_status || '') ? <Link className="btn" href="/trainer-dashboard/verification">Se trenertilgang</Link> : <Link className="btn secondary" href="/bli-trener#soknad">Se søknaden</Link>}</div>{trainerAccount.verification_status === 'pending' ? <p className="muted">Du kan fortsette å bruke Hundetimer som kunde mens søknaden vurderes. Etter godkjenning fullfører du Stripe-oppsettet før trenerdashboardet åpnes.</p> : null}{trainerAccount.verification_status === 'rejected' ? <p className="muted">{trainerAccount.verification_review_note || 'Se tilbakemeldingen og send søknaden på nytt.'}</p> : null}</section> : null}
    <section className="dashboard-section account-dogs" id="hunder"><div className="section-title"><div><span className="eyebrow">Mine hunder</span><h2>{(dogs||[]).length?'Hundeprofiler':'Legg til hunden din'}</h2></div><Link className="btn secondary compact" href="/account/dogs">Administrer hunder</Link></div>{(dogs||[]).length?<div className="account-dog-grid">{dogs!.map(dog=><Link href="/account/dogs" className="account-dog-card" key={dog.id}><div className="dog-avatar-placeholder small"><Dog size={24} aria-hidden="true" /></div><div><strong>{dog.name}</strong><span>{[dog.breed,ageText(dog.birth_date)].filter(Boolean).join(' · ')||'Profil klar for bestilling'}</span></div></Link>)}</div>:<div className="empty-state compact-empty"><div className="empty-icon">🐾</div><h3>Ingen hunder ennå</h3><p className="muted">Lagre hunden én gang, så kan du velge den direkte når du bestiller trening.</p><Link className="btn" href="/account/dogs">Legg til hund</Link></div>}</section>

    <section className="dashboard-section account-bookings" id="privattimer"><div className="section-title"><div><span className="eyebrow">Privattimer</span><h2>Bestillinger</h2></div><Link className="btn secondary" href="/discover?type=trainers">Finn trening</Link></div>{(bookings||[]).length?<div className="booking-list">{bookings!.map(booking=>{const trainer=trainerMap.get(booking.trainer_id);return <Link href={`/booking/${booking.id}`} className="account-booking-card" key={booking.id}><div><span className={`status ${booking.expired_at?'expired':booking.status}`}>{booking.expired_at?'Utløpt':(statusText[booking.status]||booking.status)}</span><h3>{booking.dog_name||'Hund'} · {serviceMap.get(booking.service_id)||'Hundetrening'}</h3><p className="muted">{trainer?.business_name||'Hundetrener'} · {dateTime(booking.requested_starts_at)} · {booking.payment_status==='authorized'?'kort reservert':booking.payment_status==='captured'?'betalt':booking.payment_status==='cancelled'?'reservasjon frigitt':booking.refund_status==='succeeded'?'refundert':booking.refund_status==='pending'?'refusjon behandles':'betaling behandles'}</p></div><div className="account-booking-price"><strong>{booking.subtotal_nok+booking.service_fee_nok} kr</strong><span>{bookingsWithLessonNotes.has(booking.id)?'Oppsummering klar →':booking.status==='completed'&&!reviewedBookings.has(booking.id)?'Gi vurdering →':booking.status==='completed'?'Se vurdering →':'Se detaljer →'}</span></div></Link>})}</div>:<div className="empty-state compact-empty"><h3>Ingen privattimer ennå</h3></div>}</section>

    <section className="dashboard-section account-online-courses" id="nettkurs"><div className="section-title"><div><span className="eyebrow">Nettkurs</span><h2>Mine kurs</h2></div><Link className="btn secondary" href="/online-courses">Finn nettkurs</Link></div>{(onlinePurchases||[]).length?<div className="online-course-account-grid">{onlinePurchases!.map(purchase=>{const course=onlineCourseMap.get(purchase.course_id);const trainer=course?onlineTrainerMap.get(course.trainer_id):null;return <Link className="online-course-account-card" href={`/learn/${purchase.id}`} key={purchase.id}>{course?.cover_image_url?<img src={course.cover_image_url} alt=""/>:<div className="course-cover-placeholder">▶</div>}<div><span className="status confirmed">{purchase.course_completed_at?'Fullført':'Tilgang aktiv'}</span><h3>{course?.title||'Nettkurs'}</h3><p className="muted small">{trainer?.business_name||'Hundetrener'}{purchase.dog_name?` · ${purchase.dog_name}`:''}</p><strong>{purchase.course_completed_at&&purchase.certificate_id?'Kursbevis klart →':'Fortsett kurset →'}</strong></div></Link>})}</div>:<div className="empty-state compact-empty"><h3>Ingen nettkurs ennå</h3><p className="muted">Kjøpte nettkurs blir tilgjengelige her med en gang.</p></div>}</section>

    {(waitlist||[]).length ? <section className="dashboard-section account-waitlists"><div className="section-title"><div><span className="eyebrow">Ventelister</span><h2>Venter på plass</h2></div></div><div className="booking-list">{waitlist!.map(entry=>{const offering=offeringMap.get(entry.offering_id); const trainer=offering?groupTrainerMap.get(offering.trainer_id):null; return <Link href={`/activities/${entry.offering_id}`} className="account-booking-card" key={entry.id}><div><span className={`status ${entry.status === 'offered' ? 'confirmed' : 'pending'}`}>{entry.status === 'offered' ? 'Plass tilgjengelig' : entry.status === 'checkout' ? 'Betaling pågår' : 'På venteliste'}</span><h3>{entry.dog_name} · {offering?.title||'Kurs/arrangement'}</h3><p className="muted">{trainer?.business_name||'Hundetrener'}{entry.offer_expires_at&&entry.status==='offered'?` · reserveres til ${formatOsloDateTime(entry.offer_expires_at)}`:''}</p></div><div className="account-booking-price"><span>{entry.status==='offered'?'Bestill plassen →':'Se ventelisten →'}</span></div></Link>})}</div></section> : null}

    <section className="dashboard-section account-group-bookings" id="gruppekurs"><div className="section-title"><div><span className="eyebrow">Kurs og arrangementer</span><h2>Påmeldinger</h2></div><Link className="btn secondary" href="/activities">Finn kurs</Link></div>{(groupEnrollments||[]).length?<div className="booking-list">{groupEnrollments!.map(enrollment=>{const offering=offeringMap.get(enrollment.offering_id); const trainer=offering?groupTrainerMap.get(offering.trainer_id):null; const firstSession=((groupSessions||[]) as MiniSession[]).find(s=>s.offering_id===enrollment.offering_id); return <Link href={`/activity-booking/${enrollment.id}`} className="account-booking-card" key={enrollment.id}><div><span className={`status ${enrollment.status}`}>{groupStatusText[enrollment.status]||enrollment.status}</span><h3>{enrollment.dog_name} · {offering?.title||'Kurs/arrangement'}</h3><p className="muted">{trainer?.business_name||'Hundetrener'}{firstSession?` · ${formatOsloDateTime(firstSession.starts_at)}`:''} · {offering?.kind==='event'?'arrangement':'kurs'}</p></div><div className="account-booking-price"><strong>{enrollment.subtotal_nok+enrollment.service_fee_nok} kr</strong><span>Se detaljer →</span></div></Link>})}</div>:<div className="empty-state compact-empty"><h3>Ingen kurspåmeldinger ennå</h3><p className="muted">Finn gruppekurs og arrangementer nær deg.</p></div>}</section>
  </main>;
}
