 'use server';
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { activeRecipients, newsletterHtml, sendNewsletterEmail } from '@/lib/newsletter/server';
const BASE=(process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000').replace(/\/$/,'');
function s(fd:FormData,k:string){return String(fd.get(k)||'').trim();}
async function ctx(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login?next=/trainer-dashboard/newsletter');const {data:t}=await supabase.from('trainer_profiles').select('id,business_name').eq('id',user.id).maybeSingle();if(!t)redirect('/trainer-onboarding');return {user,trainer:t,admin:createAdminClient()};}
export async function createTrainerCampaignAction(fd:FormData){const {user,admin}=await ctx();const title=s(fd,'title'),subject=s(fd,'subject'),body=s(fd,'body'),audience=s(fd,'audience')||'all';if(!title||!subject||!body)redirect('/trainer-dashboard/newsletter?error=Fyll+ut+alle+obligatoriske+felt');const {error}=await admin.from('newsletter_campaigns').insert({scope:'trainer',trainer_id:user.id,created_by:user.id,title,subject,preheader:s(fd,'preheader')||null,body,cta_label:s(fd,'ctaLabel')||null,cta_url:s(fd,'ctaUrl')||null,audience});if(error)redirect(`/trainer-dashboard/newsletter?error=${encodeURIComponent(error.message)}`);revalidatePath('/trainer-dashboard/newsletter');redirect('/trainer-dashboard/newsletter?message=Utkast+opprettet');}
export async function sendTrainerCampaignAction(fd:FormData){const {user,trainer,admin}=await ctx();const id=s(fd,'campaignId');const {data:c}=await admin.from('newsletter_campaigns').select('*').eq('id',id).eq('trainer_id',user.id).maybeSingle();if(!c)redirect('/trainer-dashboard/newsletter?error=Fant+ikke+nyhetsbrevet');if(c.status!=='draft')redirect('/trainer-dashboard/newsletter?error=Nyhetsbrevet+er+allerede+behandlet');const recipients=(await activeRecipients({scope:'trainer',trainer_id:user.id,audience:c.audience})).slice(0,500);if(!recipients.length)redirect('/trainer-dashboard/newsletter?error=Ingen+abonnenter+i+denne+gruppen');const {data:claimed,error:claimError}=await admin.from('newsletter_campaigns').update({status:'sending',recipient_count:recipients.length,last_error:null}).eq('id',id).eq('trainer_id',user.id).eq('status','draft').select('id').maybeSingle();if(claimError||!claimed)redirect('/trainer-dashboard/newsletter?error=Utsendelsen+kunne+ikke+startes');let sent=0,failed=0;const auth=await admin.auth.admin.getUserById(user.id);const replyTo=auth.data.user?.email||null;for(const r of recipients){const unsub=`${BASE}/newsletter/unsubscribe?token=${r.unsubscribe_token}`;const html=newsletterHtml({title:c.title,preheader:c.preheader,body:c.body,ctaLabel:c.cta_label,ctaUrl:c.cta_url,unsubscribeUrl:unsub,senderName:trainer.business_name});const {data:d}=await admin.from('newsletter_deliveries').upsert({campaign_id:id,subscription_id:r.id,email:r.email,status:'pending'},{onConflict:'campaign_id,email'}).select('id').single();try{const provider=await sendNewsletterEmail({to:r.email,subject:c.subject,html,unsubscribeToken:r.unsubscribe_token,replyTo});sent++;if(d)await admin.from('newsletter_deliveries').update({status:'sent',provider_id:provider,sent_at:new Date().toISOString()}).eq('id',d.id);}catch(e){failed++;if(d)await admin.from('newsletter_deliveries').update({status:'failed',error_message:e instanceof Error?e.message:String(e)}).eq('id',d.id);}}await admin.from('newsletter_campaigns').update({status:failed&&sent===0?'failed':'sent',sent_count:sent,failed_count:failed,sent_at:new Date().toISOString(),last_error:failed?`${failed} sendinger feilet`:null}).eq('id',id);revalidatePath('/trainer-dashboard/newsletter');redirect(`/trainer-dashboard/newsletter?message=${encodeURIComponent(`Sendt til ${sent} mottakere.`)}`);}
