import { SubmitButton } from '@/components/submit-button';
import Link from 'next/link';
import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {createAdminClient} from '@/lib/supabase/admin';
import {createTrainerCampaignAction,sendTrainerCampaignAction} from './actions';
function dt(v:string){return new Intl.DateTimeFormat('nb-NO',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Oslo'}).format(new Date(v));}
export default async function TrainerNewsletterPage({searchParams}:{searchParams:Promise<{message?:string;error?:string}>}){
 const q=await searchParams; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/login?next=/trainer-dashboard/newsletter');
 const {data:t}=await supabase.from('trainer_profiles').select('business_name').eq('id',user.id).maybeSingle(); if(!t)redirect('/trainer-onboarding'); const admin=createAdminClient();
 const [{data:campaigns},{data:subs}]=await Promise.all([admin.from('newsletter_campaigns').select('*').eq('trainer_id',user.id).order('created_at',{ascending:false}).limit(50),admin.from('newsletter_subscriptions').select('id,source').eq('scope','trainer').eq('trainer_id',user.id).is('unsubscribed_at',null)]);
 const total=subs?.length||0, marketplace=(subs||[]).filter(s=>s.source==='marketplace').length, external=(subs||[]).filter(s=>s.source==='external').length;
 return <main className="dashboard editor-page"><Link className="back-link" href="/trainer-dashboard">← Til trenerdashbord</Link><section className="dashboard-heading"><div><span className="eyebrow">Markedsføring</span><h1>Nyhetsbrev</h1><p className="muted">Send nyheter til kunder som aktivt har valgt å høre fra {t.business_name}.</p></div></section>
 {q.message?<div className="notice success">{q.message}</div>:null}{q.error?<div className="notice error">{q.error}</div>:null}
 <section className="dashboard-section"><div className="stats-grid"><div className="stat-card"><strong>{total}</strong><span>abonnenter totalt</span></div><div className="stat-card"><strong>{marketplace}</strong><span>plattformabonnenter</span></div><div className="stat-card"><strong>{external}</strong><span>eksterne kunder</span></div></div><p className="muted small">Eksterne kunder må merkes med eksplisitt nyhetsbrevsamtykke i kunderegisteret. Plattformabonnenter kan abonnere fra trenerprofilen.</p></section>
 <section className="dashboard-section"><div className="section-title"><div><span className="eyebrow">Nytt nyhetsbrev</span><h2>Lag nyhetsbrev</h2></div></div><form action={createTrainerCampaignAction} className="form-grid editor-form-grid"><label>Intern tittel<input name="title" required placeholder="Nytt valpekurs"/></label><label>Mottakere<select name="audience" defaultValue="all"><option value="all">Alle abonnenter</option><option value="marketplace">Plattformabonnenter</option><option value="external">Eksterne kunder</option></select></label><label className="full">Emnefelt<input name="subject" required placeholder="Nytt valpekurs starter snart"/></label><label className="full">Forhåndstekst<input name="preheader"/></label><label className="full">Innhold<textarea name="body" rows={10} required/></label><label>Knappetekst<input name="ctaLabel" placeholder="Se kurset"/></label><label>Knappelenke<input type="url" name="ctaUrl" placeholder="https://..."/></label><div className="full"><button className="btn">Lagre som utkast</button></div></form></section>
 <section className="dashboard-section"><div className="section-title"><div><span className="eyebrow">Historikk</span><h2>Utsendelser</h2></div></div><div className="booking-list">{(campaigns||[]).map(c=>{const eligible=Math.min(500,c.audience==='marketplace'?marketplace:c.audience==='external'?external:total);return <article className="booking-row" key={c.id}><div><strong>{c.title}</strong><span>{c.subject} · {c.audience==='all'?'Alle':c.audience==='marketplace'?'Plattformabonnenter':'Eksterne kunder'}</span><span className="muted small">{c.sent_at?dt(c.sent_at):dt(c.created_at)} · {c.sent_count||0} sendt · {c.failed_count||0} feilet</span></div>{c.status==='draft'?<details className="newsletter-review"><summary>Se utkast og send</summary><strong>{c.subject}</strong>{c.preheader ? <p className="muted">{c.preheader}</p> : null}<div className="newsletter-preview">{c.body}</div>{c.cta_url ? <p>{c.cta_label || 'Lenke'}: {c.cta_url}</p> : null}<p className="muted small">Sendes til {eligible} abonnenter med samtykke. Maks 500 mottakere per utsendelse.</p><form action={sendTrainerCampaignAction}><input type="hidden" name="campaignId" value={c.id}/><SubmitButton className="btn compact" type="submit" disabled={!eligible}>Send til {eligible}</SubmitButton></form></details>:<span className="status confirmed">{c.status==='sent'?'Sendt':c.status==='sending'?'Sender':c.status==='failed'?'Sending feilet':'Utkast'}</span>}</article>})}{!campaigns?.length?<p className="muted">Ingen utsendelser ennå.</p>:null}</div></section>
 </main>;
}
