const assert=require('node:assert/strict');const {chromium}=require('C:/Users/aidy6/AppData/Local/npm-cache/_npx/420ff84f11983ee5/node_modules/playwright');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Users/aidy6/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe'});const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://localhost:3000';for(const width of [1440,1024,768,390,320]){await p.setViewportSize({width,height:950});await p.goto(base+'/online-courses',{waitUntil:'networkidle'});const consent=p.getByRole('button',{name:'Kun nødvendige',exact:true});if(await consent.isVisible())await consent.click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:`.review/catalogue-${width}.png`,fullPage:true});console.log('Layout',width,'cards',await p.locator('.discover-card').count());}
assert(await p.locator('.discover-card').count()>0);assert.equal(await p.locator('#discover-filter-fields').isVisible(),false);await p.locator('.discover-filter-toggle').click();await p.locator('input[name=maxPrice]').fill('800');await p.locator('.catalogue-apply').click();await p.waitForURL('**maxPrice=800**');for(const t of await p.locator('.discover-card-footer strong').allTextContents())assert(Number(t.replace(/[^0-9]/g,''))<=800);console.log('PASS mobile filters and prices');
await p.locator('.catalogue-sort select').selectOption('price');await p.waitForURL('**sort=price**');assert.equal(new URL(p.url()).searchParams.get('maxPrice'),'800');const prices=(await p.locator('.discover-card-footer strong').allTextContents()).map(t=>Number(t.replace(/[^0-9]/g,'')));assert.deepEqual(prices,[...prices].sort((a,b)=>a-b));console.log('PASS sorting preserves filters');
await p.locator('.discover-active-filters a[aria-label]').first().click();await p.waitForURL(u=>!u.searchParams.has('maxPrice'));assert.equal(new URL(p.url()).searchParams.get('sort'),'price');assert.equal(await p.locator('input[name=maxPrice]').inputValue(),'');
await p.locator('input[name=q]').fill('Carina');await p.locator('.catalogue-search button').click();await p.waitForURL('**q=Carina**');assert(await p.locator('.discover-card').count()>0);assert.equal(new URL(p.url()).searchParams.get('sort'),'price');console.log('PASS search by trainer and sort persistence');
await p.goto(base+'/online-courses?level=beginner&duration=medium',{waitUntil:'networkidle'});for(const category of await p.locator('.discover-card-category').allTextContents())assert.equal(category,'Nybegynner');assert(await p.locator('.discover-card').count()>0);console.log('PASS level and duration filters');
await p.locator('.discover-card .save-button').first().click();await p.waitForURL('**/login?next=**');const next=new URL(p.url()).searchParams.get('next');assert(next.includes('level=beginner')&&next.includes('duration=medium'));console.log('PASS save preserves filtered return path');
await p.goto(base+'/online-courses?q=zzzzunmatched',{waitUntil:'networkidle'});assert.equal(await p.locator('.catalogue-empty').count(),1);await p.locator('.catalogue-empty .btn').click();await p.waitForURL(base+'/online-courses');assert.equal(await p.locator('input[name=q]').inputValue(),'');console.log('PASS empty search/reset');
const href=await p.locator('.discover-card-action').first().getAttribute('href');const r=await p.goto(base+href,{waitUntil:'networkidle'});assert.equal(r.status(),200);console.log('PASS course detail link');assert.deepEqual(errors,[]);console.log('PASS no page errors');await b.close()})().catch(e=>{console.error(e);process.exit(1)})
