const fs=require('fs');
const pages=[['app/account/page.tsx','/account'],['app/account/dogs/page.tsx','/account/dogs'],['app/account/privacy/page.tsx','/account/privacy'],['app/saved/page.tsx','/saved'],['app/notifications/page.tsx','/notifications'],['app/messages/page.tsx','/messages'],['app/messages/[bookingId]/page.tsx','/messages'],['app/booking/[id]/page.tsx','/account'],['app/activity-booking/[id]/page.tsx','/account']];
for(const [p,current] of pages){let s=fs.readFileSync(p,'utf8');s="import { CustomerNavigation } from '@/components/customer-navigation';\nimport '@/components/customer-pages.css';\n"+s;
s=s.replace(/<main className="([^"]*)">/g,(_,cls)=>`<main className="${cls.replace(/^shell /,'page-shell ')} customer-page"><CustomerNavigation current="${current}" />`);
s=s.replaceAll('className="form-success"','className="form-success" role="status"').replaceAll('className="form-error form-error-block"','className="form-error form-error-block" role="alert"');fs.writeFileSync(p,s);}
let p='app/account/page.tsx';let s=fs.readFileSync(p,'utf8');s="import { Dog } from 'lucide-react';\n"+s;
const marker='  return <main className="page-shell narrow customer-page">';
s=s.replace(marker,`  const upcoming = [
    ...(bookings || []).filter(b => b.status === 'confirmed' && !b.expired_at && new Date(b.requested_starts_at).getTime() > Date.now()).map(b => ({ id: b.id, startsAt: b.requested_starts_at, title: serviceMap.get(b.service_id) || 'Privattime', dog: b.dog_name, href: '/booking/' + b.id })),
    ...(groupEnrollments || []).filter(e => e.status === 'confirmed').flatMap(e => { const next = (groupSessions || []).find(s => s.offering_id === e.offering_id && new Date(s.starts_at).getTime() > Date.now()); return next ? [{ id: e.id, startsAt: next.starts_at, title: offeringMap.get(e.offering_id)?.title || 'Kurs', dog: e.dog_name, href: '/activity-booking/' + e.id }] : []; }),
  ].sort((a,b) => new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime());
  const nextAppointment = upcoming[0];
  const needsResponse = (bookings || []).filter(b => b.status === 'reschedule_offered' && !b.expired_at);
  const availablePlaces = (waitlist || []).filter(w => w.status === 'offered' && (!w.offer_expires_at || new Date(w.offer_expires_at).getTime() > Date.now()));

`+marker);
const hub=`
    <div className="hub-overview"><section className="hub-next"><span>{nextAppointment ? 'Neste avtale' : 'Din neste trening'}</span><h2>{nextAppointment?.title || 'Finn trening som passer dere'}</h2>{nextAppointment ? <><strong>{dateTime(nextAppointment.startsAt)}</strong><p>{nextAppointment.dog || 'Hund'}{upcoming.length > 1 ? ' · ' + upcoming.length + ' kommende avtaler' : ''}</p><Link className="btn" href={nextAppointment.href}>Se avtalen</Link></> : <><p>Når du har en bekreftet time eller kurspåmelding, finner du neste avtale her.</p><Link className="btn" href="/discover">Finn hundetrening</Link></>}</section><div className="hub-shortcuts"><Link href="/messages"><strong>Meldinger</strong><span>Spørsmål og oppfølging fra treneren →</span></Link><Link href="/saved"><strong>Lagret</strong><span>Trenere og kurs du vil finne igjen →</span></Link><Link href="#nettkurs"><strong>Mine nettkurs</strong><span>{(onlinePurchases || []).length ? (onlinePurchases || []).length + ' kurs tilgjengelig · fortsett treningen →' : 'Se kursene dine →'}</span></Link></div></div>
    {needsResponse.length || availablePlaces.length ? <section className="hub-attention"><h2>Venter på svar fra deg</h2>{needsResponse.map(b => <Link key={b.id} href={'/booking/' + b.id}>Ny tid foreslått: {serviceMap.get(b.service_id) || 'Privattime'}</Link>)}{availablePlaces.map(w => <Link key={w.id} href={'/activities/' + w.offering_id}>Plass tilgjengelig: {offeringMap.get(w.offering_id)?.title || 'Kurs'}</Link>)}</section> : null}
    <nav className="hub-section-links" aria-label="Dine bestillinger"><a href="#hunder">Hunder</a><a href="#privattimer">Privattimer</a><a href="#nettkurs">Nettkurs</a><a href="#gruppekurs">Kurs og arrangementer</a></nav>
`;
s=s.replace('    {trainerAccount ?',hub+'    {trainerAccount ?');
for(const [cls,id] of [['account-dogs','hunder'],['account-bookings','privattimer'],['account-online-courses','nettkurs'],['account-group-bookings','gruppekurs']])s=s.replace(`className="dashboard-section ${cls}"`,`className="dashboard-section ${cls}" id="${id}"`);
s=s.replace('<article className="account-dog-card" key={dog.id}>','<Link href="/account/dogs" className="account-dog-card" key={dog.id}>').replace('</div></article>)}</div>','</div></Link>)}</div>');s=s.replace('>🐕</div>','><Dog size={24} aria-hidden="true" /></div>');fs.writeFileSync(p,s);
p='app/account/dogs/page.tsx';s=fs.readFileSync(p,'utf8');s="import { Dog } from 'lucide-react';\nimport { safeAuthNext } from '@/lib/auth-next';\n"+s;s=s.replace('<div className="section-title"><div><span className="eyebrow">Ny hund</span><h2>Legg til hund</h2></div></div>','<details open={!dogs?.length || Boolean(next)}><summary>Legg til hund</summary><p className="muted small">Navn er obligatorisk. Resten kan du fylle ut senere.</p>');s=s.replace('        </form>\n      </section>','        </form></details>\n      </section>');s=s.replace('value={next}','value={safeAuthNext(next, \'/account/dogs\')}');s=s.replace('<input type="hidden" name="id" value={dog.id} />\n                  <label>','<input type="hidden" name="id" value={dog.id} />\n                  {next && <input type="hidden" name="next" value={safeAuthNext(next, \'/account/dogs\')} />}\n                  <label>');s=s.replace('>🐕</div>','><Dog size={26} aria-hidden="true" /></div>');fs.writeFileSync(p,s);
p='app/account/dogs/actions.ts';s=fs.readFileSync(p,'utf8').replace("import { revalidatePath }", "import { safeAuthNext } from '@/lib/auth-next';\nimport { revalidatePath }");s=s.replace("if (next && next.startsWith('/')) redirect(next);","if (next) redirect(safeAuthNext(next, '/account/dogs'));");fs.writeFileSync(p,s);
p='app/account/privacy/page.tsx';s=fs.readFileSync(p,'utf8');s=s.replace('<h1>Dine data</h1>','<h1>Personvern og konto</h1>');s=s.replace('Markedsføring på e-post','Nyhetsbrev og tilbud fra Hundetimer').replace('Ingen slik analyse er aktivert i MVP-en nå.','Ingen slik analyse er aktivert nå.');s=s.replace('name="confirmation" autoComplete','name="confirmation" required autoComplete');s=s.replace('    <section className="dashboard-section"><div className="section-title"><div><span className="eyebrow">Dataeksport','    <div className="privacy-sections"><section className="dashboard-section"><div className="section-title"><div><span className="eyebrow">Dataeksport');s=s.replace('    <p><Link href={profile?.role','    </div><p><Link href={profile?.role');fs.writeFileSync(p,s);
p='app/messages/page.tsx';s=fs.readFileSync(p,'utf8');s=s.replace('  return <main',`  bookings.sort((a, b) => new Date(lastByBooking.get(b.id)?.created_at || b.created_at).getTime() - new Date(lastByBooking.get(a.id)?.created_at || a.created_at).getTime());
  return <main`);s=s.replace('<h1>Samtaler om bestillinger</h1>','<h1>Meldinger</h1>');fs.writeFileSync(p,s);
p='components/booking-chat.tsx';s=fs.readFileSync(p,'utf8');s=s.replace('<div className="chat-messages" aria-live="polite">','<div className="chat-messages" role="log" aria-label="Samtale" aria-live="polite">');s=s.replace('<textarea value={body}','<label htmlFor="booking-message">Din melding</label><textarea id="booking-message" value={body}');s=s.replace('className="form-error"','className="form-error" role="alert"');fs.writeFileSync(p,s);
p='app/activity-booking/[id]/page.tsx';s=fs.readFileSync(p,'utf8');s=s.replace('    : { data: null };','    : { data: null };\n  if (!offering) redirect(\'/account\');');s=s.replace('<span>Betalt</span>','<span>{enrollment.payment_status === \'refunded\' || enrollment.status === \'refunded\' ? \'Refundert\' : enrollment.payment_status === \'captured\' ? \'Betalt\' : \'Totalt\'}</span>');fs.writeFileSync(p,s);
p='app/booking/[id]/page.tsx';s=fs.readFileSync(p,'utf8');s=s.replace("if (!booking) notFound();","if (!booking || ![booking.customer_id, booking.trainer_id].includes(user.id)) notFound();");fs.writeFileSync(p,s);
