const {chromium}=require('C:/Users/aidy6/AppData/Local/npm-cache/_npx/420ff84f11983ee5/node_modules/playwright');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:'C:/Users/aidy6/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe'});const page=await browser.newPage({viewport:{width:390,height:844}});
await page.goto('http://localhost:3000/discover',{waitUntil:'networkidle'});
const links=await page.locator('main a[href]').evaluateAll(a=>a.map(x=>x.getAttribute('href')).filter(x=>/^\/(trainers|activities|online-courses)\//.test(x))); console.log('Detail pages found:',links.length);
for(const prefix of ['/trainers/','/activities/','/online-courses/']){const link=links.find(x=>x.startsWith(prefix));if(!link)continue;await page.goto('http://localhost:3000'+link,{waitUntil:'networkidle'});console.log(JSON.stringify({route:link,overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),heading:await page.locator('h1').allTextContents()}));await page.screenshot({path:'.review/detail'+prefix.replaceAll('/','_')+'.png',fullPage:true});}
await page.goto('http://localhost:3000/discover?type=activities',{waitUntil:'networkidle'});await page.locator('.discovery-advanced summary').click();console.log('Activities retained:',await page.locator('select[name=type]').inputValue());await page.locator('input[name=maxPrice]').fill('1000');await page.getByRole('button',{name:'Vis treff',exact:true}).click();await page.waitForURL('**/discover?**maxPrice=1000**');console.log('Filter submitted:',new URL(page.url()).searchParams.get('maxPrice'),'expanded:',await page.locator('.discovery-advanced').getAttribute('open'));await page.screenshot({path:'.review/filters-mobile.png',fullPage:true});
await page.goto('http://localhost:3000/discover?q=zzzznonexistent',{waitUntil:'networkidle'});console.log('Empty states:',await page.locator('.empty-state').count());
await page.goto('http://localhost:3000');await page.locator('.welcome-search input[name=q]').fill('valp');await page.locator('.welcome-search input[name=place]').fill('Hamar');await page.getByRole('button',{name:'Finn trening',exact:true}).click();await page.waitForURL('**/discover?**');console.log('Home search:',new URL(page.url()).search);
await page.setViewportSize({width:1440,height:900});await page.goto('http://localhost:3000/discover',{waitUntil:'networkidle'});await page.screenshot({path:'.review/discover-desktop.png',fullPage:true});
await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
