const {load,fixtures,db,overrides}=require('./customer-fixtures.cjs');const assert=require('node:assert/strict'),fs=require('fs'),{renderToStaticMarkup}=require('react-dom/server');
let pathname='/trainer-dashboard/verification';overrides['next/headers']={headers:async()=>new Headers({'x-hundetimer-pathname':pathname})};overrides['@/components/trainer-dashboard-sidebar']={TrainerDashboardSidebar:()=>null};overrides['@/lib/notifications/server']={bestEffortNotification:async()=>{}};
(async()=>{const {trainerJourneyStage, stripePayoutReady}=load('lib/trainer-journey.ts');const payment={stripe_account_id:'acct_review',details_submitted:true,payouts_enabled:true,transfers_active:true};const base={role:'owner',status:'pending'};const cases=[['application',{}],['review',base],['sign',{...base,agreementSent:true}],['countersign',{...base,agreementSent:true,trainerSigned:true}],['approval',{...base,agreementSent:true,trainerSigned:true,platformSigned:true}],['stripe',{role:'trainer',status:'approved',trainerSigned:true,platformSigned:true}],['ready',{role:'trainer',status:'approved',trainerSigned:true,platformSigned:true,payment}],['rejected',{...base,status:'rejected'}],['suspended',{role:'trainer',status:'suspended',payment}]];for(const [stage,input]of cases)assert.equal(trainerJourneyStage(input),stage);for(const key of ['details_submitted','payouts_enabled','transfers_active'])assert.equal(stripePayoutReady({...payment,[key]:false}),false);
const css=['app/globals.css','app/refinements.css','components/trainer-journey.css','app/bli-trener/application.css'].map(p=>fs.readFileSync(p,'utf8')).join('\n');
for(const [stage,input]of cases){fixtures.profiles=[{id:'user',role:input.role||'owner',display_name:'Andrea'}];fixtures.trainer_profiles=stage==='application'?[]:[{id:'user',business_name:'Andrea Hundetrening',verification_status:input.status,city:'Hamar'}];fixtures.trainer_verification_submissions=stage==='application'?[]:[{id:'submission',trainer_id:'user',status:input.status,submitted_at:'2026-10-01T12:00:00Z',agreement_sent_at:input.agreementSent?'2026-10-02T12:00:00Z':null}];fixtures.trainer_agreement_acceptances=input.trainerSigned?[{id:'agreement',trainer_id:'user',agreement_version:'1.0',trainer_signed_at:'2026-10-03T12:00:00Z',admin_signed_at:input.platformSigned?'2026-10-04T12:00:00Z':null}]:[];fixtures.trainer_payment_accounts=input.payment?[{trainer_id:'user',...input.payment}]:[];
const page=await load('app/trainer-dashboard/verification/page.tsx').default({searchParams:Promise.resolve({})});const html=renderToStaticMarkup(page);fs.writeFileSync('.review/journey-'+stage+'.html','<!doctype html><html lang="nb"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style><body>'+html+'</body></html>');assert(!html.includes('Godta treneravtalen'));if(stage==='sign')assert(html.includes('Les og signer treneravtalen'));if(stage==='stripe')assert(html.includes('/api/stripe/connect/onboard'));if(stage==='ready')assert(html.includes('Åpne trenerdashboard'));
pathname='/trainer-dashboard/verification';await load('app/trainer-dashboard/layout.tsx').default({children:'status'});pathname='/trainer-dashboard';if(stage==='ready')await load('app/trainer-dashboard/layout.tsx').default({children:'workspace'});else await assert.rejects(()=>load('app/trainer-dashboard/layout.tsx').default({children:'workspace'}),/redirect \/trainer-dashboard\/verification/);}
assert.throws(()=>load('app/trainer-onboarding/page.tsx').default(),/redirect \/trainer-dashboard\/verification/);await assert.rejects(()=>load('app/trainer-dashboard/verification/agreement-actions.ts').acceptTrainerAgreementAction(new FormData()),/redirect \/vilkar\/treneravtale/);
console.log('PASS all nine journey states, each Stripe readiness flag, applicant status access, dashboard gate, legacy route and agreement-action redirects. Local fixtures only.');})().catch(e=>{console.error(e);process.exit(1)});
