const {load,fixtures,db}=require('./customer-fixtures.cjs');const {renderToStaticMarkup}=require('react-dom/server');const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
const purchase=fixtures.online_course_purchases[0];Object.assign(purchase,{course_completed_at:null,certificate_id:null});
const course=fixtures.online_courses[0];Object.assign(course,{certificate_enabled:true});
fixtures.online_course_modules=[{id:'module2',course_id:'course',title:'På tur',position:2},{id:'module1',course_id:'course',title:'Kom i gang',position:1}];
fixtures.online_course_lessons=[{id:'lesson3',course_id:'course',module_id:'module2',title:'Øv på tur',position:1,duration_minutes:10},{id:'lesson2',course_id:'course',module_id:'module1',title:'Kontakt og belønning',position:2,duration_minutes:8},{id:'lesson1',course_id:'course',module_id:'module1',title:'Før dere begynner',position:1,duration_minutes:5}];
fixtures.online_course_progress=[{purchase_id:'purchase',lesson_id:'lesson1',completed_at:'2026-10-01T10:00:00Z'},{purchase_id:'purchase',lesson_id:'removed-lesson',completed_at:'2026-10-01T10:00:00Z'}];
fixtures.online_course_lesson_content=fixtures.online_course_lessons.map(l=>({lesson_id:l.id,body_text:'Finn et rolig sted hvor hunden kan konsentrere seg.\nBelønn kontakt og ta korte pauser. Gjenta øvelsen i deres eget tempo.'}));
const {orderedCourseLessons,completedCourseLessons,hasPaidCourseAccess}=load('lib/course-learning.ts');assert.deepEqual(orderedCourseLessons(fixtures.online_course_modules,fixtures.online_course_lessons).map(x=>x.id),['lesson1','lesson2','lesson3']);assert.equal(completedCourseLessons(fixtures.online_course_lessons,fixtures.online_course_progress).size,1);for(const payment_status of ['authorized','checkout_pending','failed','refunded'])assert.equal(hasPaidCourseAccess({status:'active',payment_status}),false);
// Mirror ordered query results for rendering after independently checking the sorter above.
fixtures.online_course_modules.sort((a,b)=>a.position-b.position);
const css=['app/globals.css','app/refinements.css','components/customer-pages.css','app/learn/learning.css'].map(f=>fs.readFileSync(f,'utf8')).join('\n');
async function render(name,file,params,searchParams={}){const html=renderToStaticMarkup(await load(file).default({params:Promise.resolve(params),searchParams:Promise.resolve(searchParams)}));fs.writeFileSync('.review/learning-'+name+'.html','<!doctype html><html lang="nb"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>'+css+'</style><body>'+html+'</body></html>');return html;}
const home=await render('overview','app/learn/[purchaseId]/page.tsx',{purchaseId:'purchase'});assert(home.includes('/learn/purchase/lesson/lesson2'));assert(home.includes('1 av 3 leksjoner'));
for(const id of ['lesson1','lesson2','lesson3']){const html=await render(id,'app/learn/[purchaseId]/lesson/[lessonId]/page.tsx',{purchaseId:'purchase',lessonId:id});assert.equal((html.match(/<main[ >]/g)||[]).length,1);assert(html.includes('aria-current="page"'));if(id==='lesson2'){assert(html.includes('/lesson/lesson1'));assert(html.includes('/lesson/lesson3'));}if(id==='lesson3')assert(html.includes('Se fremgang og fullføring'));}
purchase.payment_status='authorized';await assert.rejects(()=>load('app/learn/[purchaseId]/lesson/[lessonId]/page.tsx').default({params:Promise.resolve({purchaseId:'purchase',lessonId:'lesson1'}),searchParams:Promise.resolve({})}),/redirect/);const blocked=await render('unpaid','app/learn/[purchaseId]/page.tsx',{purchaseId:'purchase'});assert(!blocked.includes('/lesson/lesson1'));purchase.payment_status='captured';
fixtures.online_course_purchases.push({...purchase,id:'unpaid-purchase',payment_status:'authorized'},{...purchase,id:'refunded-purchase',status:'refunded'});const account=renderToStaticMarkup(await load('app/account/page.tsx').default());assert(account.includes('/learn/purchase'));assert(!account.includes('/learn/unpaid-purchase'));assert(!account.includes('/learn/refunded-purchase'));fixtures.online_course_purchases.splice(1);
Object.assign(purchase,{course_completed_at:'2026-10-02T10:00:00Z',certificate_id:'CERT-2026-REVIEW'});const complete=await render('completed','app/learn/[purchaseId]/page.tsx',{purchaseId:'purchase'});assert(complete.includes('100% fullført'));assert(complete.includes('/certificates/purchase'));assert(complete.includes('Repeter leksjoner'));await render('certificate','app/certificate/[certificateId]/page.tsx',{certificateId:purchase.certificate_id});
const pdf=await load('app/certificates/[purchaseId]/route.ts').GET(new Request('http://localhost:3000/certificates/purchase'),{params:Promise.resolve({purchaseId:'purchase'})});assert.equal(pdf.status,200);assert.equal(pdf.headers.get('content-type'),'application/pdf');const bytes=Buffer.from(await pdf.arrayBuffer());assert.equal(bytes.subarray(0,4).toString(),'%PDF');fs.writeFileSync('.review/course-certificate-preview.pdf',bytes);
purchase.payment_status='refunded';await assert.rejects(()=>load('app/certificate/[certificateId]/page.tsx').default({params:Promise.resolve({certificateId:purchase.certificate_id})}),/notFound/);assert.equal((await load('app/certificates/[purchaseId]/route.ts').GET(new Request('http://localhost:3000/certificates/purchase'),{params:Promise.resolve({purchaseId:'purchase'})})).status,404);purchase.payment_status='captured';
let calls=[];db.rpc=async(name,args)=>{calls.push({name,args});return{data:{newly_completed:false},error:null}};const notifications=load('app/notifications/actions.ts');for(const read of ['true','false']){const fd=new FormData();fd.set('id','notification');fd.set('read',read);await notifications.setNotificationReadStateAction(fd);assert.equal(calls.at(-1).args.p_read,read==='true');}await assert.rejects(()=>notifications.markAllNotificationsReadAction(),/redirect \/notifications/);assert.equal(calls.at(-1).name,'mark_all_notifications_read');
const progressAction=load('app/learn/[purchaseId]/actions.ts');const fd=new FormData();fd.set('purchaseId','purchase');fd.set('lessonId','lesson2');fd.set('complete','true');await progressAction.setLessonCompleteAction(fd);assert.equal(calls.at(-1).name,'set_online_course_lesson_complete_v2');assert.equal(calls.at(-1).args.p_complete,true);fd.set('complete','false');await progressAction.setLessonCompleteAction(fd);assert.equal(calls.at(-1).args.p_complete,false);
db.rpc=async()=>({error:{message:'offline'}});await assert.rejects(()=>notifications.markAllNotificationsReadAction(),/error=read/);await assert.rejects(()=>progressAction.setLessonCompleteAction(fd),/error=progress/);
console.log('PASS paid access, account purchase filtering, shared lesson order, progress counts, completion/revision display, certificate PDF and access, notification read/unread/all-read and progress actions incl failures (mocked DB).');
})().catch(e=>{console.error(e);process.exit(1)});
